project_id = "myrrgvflilxguuucikyq"

[functions.send-email]
verify_jwt = false

[functions.process-scheduled-campaigns]
verify_jwt = false

[functions.track-open]
verify_jwt = false

[functions.track-click]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.enqueue-email]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false
